# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gxTwWL6TTec0iCYvRSdgwGNkEO3RgiOe
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Cargar datos de BehaviorSpace que usa las primeras 6 líneas como metadatos
df = pd.read_csv('resultados_redes.csv', skiprows=6)

# Limpiar los nombres de las columnas que exporta NetLogo
df.columns = df.columns.str.replace(r'[\[\]"]', '', regex=True)
df = df.rename(columns={'tipo_red': 'Red', 'gamma': 'Gamma', 'h': 'h', 'Psi': 'Psi_val'})

#Estilo estilo visual
sns.set_theme(style="whitegrid")

# Crear la figura con 3 páneles (1 fila, 3 columnas)
g = sns.relplot(
    data=df,
    x='Gamma',
    y='Psi_val',
    hue='h',        # Distintos colores para valores de h
    col='Red',      # Un panel por cada tipo de red
    kind='line',
    marker='o',
    col_order=["látice cuadrada", "aleatoria", "libre de escala"],
    height=4,
    aspect=1
)

# Ajustar etiquetas y títulos
g.set_axis_labels(r"$\gamma$ (gamma)", r"$\Psi$ (Polarización)")
g.set_titles("Topología: {col_name}")
plt.subplots_adjust(top=0.85)
g.fig.suptitle('Efecto del Tipo de Red en la Polarización (\Psi) frente a \gamma', fontsize=14)

# Exportar y mostrar
plt.savefig("figura_3_redes.png", dpi=300, bbox_inches="tight")
plt.show()

from google.colab import drive
drive.mount('/content/drive')