# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F_KD2i8yzMVc5O3rwThtjG4qZQeZ5bAM
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")

def generar_grafica_validacion(csv_path, output_path):

    df = pd.read_csv(csv_path, skiprows=6)
    columnas = list(df.columns)
    col_densidad = columnas[-2]
    col_flujo = columnas[-1]

    # crear gráfica de dispersión
    plt.figure(figsize=(8, 6))
    sns.scatterplot(
        data=df,
        x=col_densidad,
        y=col_flujo,
        alpha=0.6,
        color='navy',
        edgecolor=None
    )

    plt.title('Diagrama Fundamental del Tráfico (Validación del Modelo)', fontsize=14)
    plt.xlabel('Densidad de autos (Autos / Distancia)', fontsize=12)
    plt.ylabel('Flujo promedio (Autos / 50 ticks)', fontsize=12)

    plt.tight_layout()
    plt.savefig(output_path, dpi=300)
    print(f"Gráfica guardada exitosamente en: {output_path}")

if __name__ == "__main__":
    generar_grafica_validacion('/datos_experimento.csv', 'validacion.png')

from google.colab import drive
drive.mount('/content/drive')